import type { ProduitPOS } from "@/store/pos.store";

export const CATEGORIES_DEMO = [
  { id: "riz", label: "Riz", labelMG: "Vary", icon: "🌾" },
  { id: "huile", label: "Huile", labelMG: "Menaka", icon: "🫙" },
  { id: "sucre", label: "Sucre", labelMG: "Siramamy", icon: "🍬" },
  { id: "savon", label: "Savon", labelMG: "Savony", icon: "🧼" },
  { id: "lait", label: "Lait", labelMG: "Ronono", icon: "🥛" },
  { id: "farine", label: "Farine", labelMG: "Harina", icon: "🌾" },
  { id: "sel", label: "Sel", labelMG: "Sira", icon: "🧂" },
  { id: "conserves", label: "Conserves", labelMG: "Boaty", icon: "🥫" },
];

export const PRODUITS_DEMO: (ProduitPOS & { categorieId: string })[] = [
  {
    id: "p-riz-maka",
    code: "RIZ-MAKA-001",
    nom: "Riz Makalioka",
    nomMG: "Vary Makalioka",
    categorieId: "riz",
    uniteBase: "kg",
    stockDisponible: 2500,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-riz-kg",
        nom: "kg",
        facteurConversion: 1,
        prixGros: 2800,
        prixSemiGros: 3000,
        prixDetail: 3200,
        codeBarres: null,
      },
      {
        id: "uv-riz-25",
        nom: "Sac 25 kg",
        facteurConversion: 25,
        prixGros: 67000,
        prixSemiGros: 72000,
        prixDetail: 76000,
        codeBarres: "6111234567890",
      },
      {
        id: "uv-riz-50",
        nom: "Sac 50 kg",
        facteurConversion: 50,
        prixGros: 130000,
        prixSemiGros: 138000,
        prixDetail: 145000,
        codeBarres: "6111234567891",
      },
    ],
  },
  {
    id: "p-riz-tsipala",
    code: "RIZ-TSIP-001",
    nom: "Riz Tsipala",
    nomMG: "Vary Tsipala",
    categorieId: "riz",
    uniteBase: "kg",
    stockDisponible: 1800,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-tsip-kg",
        nom: "kg",
        facteurConversion: 1,
        prixGros: 2400,
        prixSemiGros: 2600,
        prixDetail: 2800,
        codeBarres: null,
      },
      {
        id: "uv-tsip-50",
        nom: "Sac 50 kg",
        facteurConversion: 50,
        prixGros: 112000,
        prixSemiGros: 118000,
        prixDetail: 125000,
        codeBarres: "6111234567892",
      },
    ],
  },
  {
    id: "p-huile-tiko",
    code: "HUI-TIKO-001",
    nom: "Huile Tiko 1L",
    nomMG: "Menaka Tiko 1L",
    categorieId: "huile",
    uniteBase: "bouteille",
    stockDisponible: 600,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-hui-btl",
        nom: "Bouteille 1L",
        facteurConversion: 1,
        prixGros: 10500,
        prixSemiGros: 11000,
        prixDetail: 12000,
        codeBarres: "6111234567893",
      },
      {
        id: "uv-hui-carton",
        nom: "Carton 12 btl",
        facteurConversion: 12,
        prixGros: 118000,
        prixSemiGros: 124000,
        prixDetail: 132000,
        codeBarres: "6111234567894",
      },
    ],
  },
  {
    id: "p-sucre-blanc",
    code: "SUC-BLA-001",
    nom: "Sucre Blanc",
    nomMG: "Siramamy Fotsy",
    categorieId: "sucre",
    uniteBase: "kg",
    stockDisponible: 3000,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-suc-kg",
        nom: "kg",
        facteurConversion: 1,
        prixGros: 4200,
        prixSemiGros: 4500,
        prixDetail: 4800,
        codeBarres: null,
      },
      {
        id: "uv-suc-50",
        nom: "Sac 50 kg",
        facteurConversion: 50,
        prixGros: 195000,
        prixSemiGros: 210000,
        prixDetail: 220000,
        codeBarres: "6111234567895",
      },
    ],
  },
  {
    id: "p-savon-madar",
    code: "SAV-MAD-001",
    nom: "Savon Madar",
    nomMG: "Savony Madar",
    categorieId: "savon",
    uniteBase: "pièce",
    stockDisponible: 2400,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-sav-pce",
        nom: "Pièce",
        facteurConversion: 1,
        prixGros: 700,
        prixSemiGros: 750,
        prixDetail: 800,
        codeBarres: null,
      },
      {
        id: "uv-sav-carton",
        nom: "Carton 100 pcs",
        facteurConversion: 100,
        prixGros: 62000,
        prixSemiGros: 66000,
        prixDetail: 70000,
        codeBarres: "6111234567896",
      },
    ],
  },
  {
    id: "p-lait-gloria",
    code: "LAI-GLO-001",
    nom: "Lait Gloria concentré",
    nomMG: "Ronono Gloria",
    categorieId: "lait",
    uniteBase: "boîte",
    stockDisponible: 576,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-lai-boite",
        nom: "Boîte",
        facteurConversion: 1,
        prixGros: 4000,
        prixSemiGros: 4200,
        prixDetail: 4500,
        codeBarres: "6111234567897",
      },
      {
        id: "uv-lai-carton",
        nom: "Carton 48 boîtes",
        facteurConversion: 48,
        prixGros: 180000,
        prixSemiGros: 192000,
        prixDetail: 200000,
        codeBarres: "6111234567898",
      },
    ],
  },
  {
    id: "p-farine-mixa",
    code: "FAR-MIX-001",
    nom: "Farine Mixa",
    nomMG: "Harina Mixa",
    categorieId: "farine",
    uniteBase: "kg",
    stockDisponible: 1200,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-far-kg",
        nom: "kg",
        facteurConversion: 1,
        prixGros: 3800,
        prixSemiGros: 4000,
        prixDetail: 4200,
        codeBarres: null,
      },
      {
        id: "uv-far-sac",
        nom: "Sac 25 kg",
        facteurConversion: 25,
        prixGros: 88000,
        prixSemiGros: 94000,
        prixDetail: 98000,
        codeBarres: "6111234567899",
      },
    ],
  },
  {
    id: "p-sel-marin",
    code: "SEL-MAR-001",
    nom: "Sel marin",
    nomMG: "Sira anaty ranomasina",
    categorieId: "sel",
    uniteBase: "kg",
    stockDisponible: 5000,
    tauxTVA: 0,
    unitesVente: [
      {
        id: "uv-sel-kg",
        nom: "kg",
        facteurConversion: 1,
        prixGros: 500,
        prixSemiGros: 600,
        prixDetail: 700,
        codeBarres: null,
      },
      {
        id: "uv-sel-sac",
        nom: "Sac 50 kg",
        facteurConversion: 50,
        prixGros: 22000,
        prixSemiGros: 26000,
        prixDetail: 30000,
        codeBarres: "6111234567900",
      },
    ],
  },
];
